services:
  postgres:
    image: postgres:15-alpine
    container_name: turnos_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: turnos_reservas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: turnos_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: turnos_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"   # Puerto de la cola
      - "15672:15672" # Interfaz de gestión (UI)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  appointments-service:
    build: ./services/appointments-service
    container_name: turnos_appointments
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://user:password@postgres:5432/turnos_reservas
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped

  notifications-service:
    build: ./services/notifications-service
    container_name: turnos_notifications
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - TEST_EMAIL_RECIPIENT=ldiuchep@ucentral.edu.co
      # - RESEND_API_KEY=pon_tu_api_key_aqui
    depends_on:
      - rabbitmq
    restart: unless-stopped

  api-gateway:
    build: ./api-gateway
    container_name: turnos_gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - APPOINTMENTS_SERVICE_URL=http://appointments-service:3001
    depends_on:
      - appointments-service
    restart: unless-stopped

  client-app:
    build: ./client-app
    container_name: turnos_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
